# Generated by Django 3.1.2 on 2020-12-05 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
